name: dhuwitku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  change_app_package_name: ^1.5.0
  cloud_firestore: ^6.1.1
  dio: ^5.4.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  
  freezed_annotation: ^3.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^7.2.0
  icons_plus: ^5.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  rename_app: ^1.6.5
  shared_preferences: ^2.2.2
  yo_ui:
    git:
      url: https://github.com/cahyo40/youi.git

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env
